### ISSUE TITLE
Cannot run program "ant"

### ISSUE THREAD

**Issue by jwoertink** [iconara/puck#8]
When I just run `require 'puck'` I get this error:

```text
jruby-1.7.18 :001 > require 'puck'
IOError: Cannot run program "ant" (in directory "/Users/jeremy/Development/games/maze_craze"): error=2, No such file or directory
	from org/jruby/RubyIO.java:4345:in `popen'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/ant.rb:5:in `load_from_ant'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/ant.rb:38:in `load'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/ant.rb:61:in `Ant'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/ant.rb:3:in `(root)'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
	from /Users/jeremy/.rvm/gems/jruby-1.7.18@waves/gems/puck-1.0.0.pre4/lib/puck/jar.rb:1:in `(root)'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
	from /Users/jeremy/.rvm/gems/jruby-1.7.18@waves/gems/puck-1.0.0.pre4/lib/puck/jar.rb:7:in `(root)'
	from org/jruby/RubyKernel.java:1071:in `require'
	from /Users/jeremy/.rvm/gems/jruby-1.7.18@waves/gems/puck-1.0.0.pre4/lib/puck.rb:1:in `(root)'
	from /Users/jeremy/.rvm/gems/jruby-1.7.18@waves/gems/puck-1.0.0.pre4/lib/puck.rb:10:in `(root)'
	from org/jruby/RubyKernel.java:1107:in `eval'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:135:in `require'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1507:in `loop'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from org/jruby/RubyKernel.java:1270:in `catch'
	from /Users/jeremy/.rvm/rubies/jruby-1.7.18/bin/irb:13:in `(root)'jruby-1.7.18 :002 >
```

**Comment by iconara** [comment]
This is a weird thing with JRuby's Ant-integration, it requires Ant, but doesn't check for its presence or very nicely, and once you've installed it you never see that stack trace again so you forget about it. Most systems with a JDK even come with it installed already, OS X did until Apple stopped shipping their own JDK. I should probably add this to a troubleshooting guide in the readme.

Anway, you need to install Ant. `brew install ant` if you use Homebrew.

Sorry about the crappy experience so far, hope you will like it better once it works for you.

**Comment by jwoertink** [comment]
sweet! Yup, `brew install ant` fixed my issues. Thanks!
